package com.lcy.todo.web.dao;

import com.lcy.todo.web.dataobject.BmAuthCode;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface BmAuthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_auth_code
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    @Delete({
        "delete from bm_auth_code",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_auth_code
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    @Insert({
        "insert into bm_auth_code (user_id, id, ",
        "gmt_modified, gmt_created)",
        "values (#{userId,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, ",
        "#{gmtModified,jdbcType=TIMESTAMP}, #{gmtCreated,jdbcType=TIMESTAMP})"
    })
    int insert(BmAuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_auth_code
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    @Select({
        "select",
        "user_id, id, gmt_modified, gmt_created",
        "from bm_auth_code",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_created", property="gmtCreated", jdbcType=JdbcType.TIMESTAMP)
    })
    BmAuthCode selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_auth_code
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    @Select({
        "select",
        "user_id, id, gmt_modified, gmt_created",
        "from bm_auth_code"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_created", property="gmtCreated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BmAuthCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_auth_code
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    @Update({
        "update bm_auth_code",
        "set id = #{id,jdbcType=VARCHAR},",
          "gmt_modified = #{gmtModified,jdbcType=TIMESTAMP},",
          "gmt_created = #{gmtCreated,jdbcType=TIMESTAMP}",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BmAuthCode record);
}