package com.lcy.todo.web.dataobject;

import java.util.Date;

public class BmAuthCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_auth_code.user_id
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_auth_code.id
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_auth_code.gmt_modified
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_auth_code.gmt_created
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    private Date gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_auth_code.user_id
     *
     * @return the value of bm_auth_code.user_id
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_auth_code.user_id
     *
     * @param userId the value for bm_auth_code.user_id
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_auth_code.id
     *
     * @return the value of bm_auth_code.id
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_auth_code.id
     *
     * @param id the value for bm_auth_code.id
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_auth_code.gmt_modified
     *
     * @return the value of bm_auth_code.gmt_modified
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_auth_code.gmt_modified
     *
     * @param gmtModified the value for bm_auth_code.gmt_modified
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_auth_code.gmt_created
     *
     * @return the value of bm_auth_code.gmt_created
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_auth_code.gmt_created
     *
     * @param gmtCreated the value for bm_auth_code.gmt_created
     *
     * @mbg.generated Wed Jan 23 21:16:10 CST 2019
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}